### ISSUE TITLE
Add better explanations to the quick start page for running your first simulation

### ISSUE THREAD

**Issue by lcarasik** [Nek5000/NekDoc#113]
The current quick-start instructions for running your first simulation are difficult for a new user to Nek5000 as well as the terminal environment to understand what's going on or specifics of Nek5000.

The following needs to change:
1. Removal of compound commands (ex: cd ~/Nek5000/tools; ./maketools genmap -> split to two lines)
2. Include a link or table of what each command is from (i.e. bash commands, what tarballs are)
3. remove the "visit -o eddy_uv.nek5000" command and show a quick two path of visualizing Nek5000 with VISIT or PARAVIEW.

**Comment by dshaver-ANL** [comment]
Addressed points 1 and 3 directly. For 2, we assume the user is familiar with Unix and bash and a disclaimer stating this has been added.
