### ISSUE TITLE
Wiki as the primary source of documentation

### ISSUE THREAD

**Issue by stgeke** [Nek5000/NekDoc#12]
I suggest to use the build-in wiki on GitHub as the primary source of documentation. The wiki is a git repo in itself, so there is no need for an extra NekDoc repo. To do this we need to sort out two things: (1) How to embed Latex (2) How to convert multiple wiki pages into one combined document (as a pdf) for print. I am not an expert on this but it looks doable to me.

**Comment by RonRahaman** [comment]
I disagree.  I think the documentation should be published as a technical report.  This is what is currently done with NekDoc.

**Comment by RonRahaman** [comment]
Plus, it's a big document, I don't want to write the whole damn thing in Markdown.

**Comment by lcarasik** [comment]
I'd recommend maintaining at least a PDF manual. Use the wiki for FAQ and
links to tutorials.

More documentation is never a bad thing as long as they don't conflict with
each other.

On Sunday, July 31, 2016, Ron Rahaman <notifications@github.com> wrote:

> Plus, it's a big document, I don't want to write the whole damn thing in
> Markdown.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Nek5000_NekDoc_issues_12-23issuecomment-2D236439526&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=3VYqmJyUJudLw7jNaGhoKHxFYF6rUZoiciFnRd2hrXQ&m=PiEUP3JYQ7zaoxlnUds3craSOKNinnO28s6F6XVv4ZQ&s=fN6L9Gt0TLqei7q32O7MLAhv5sMQBOYzd98v5ATaDok&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ASr0ug7HGduQQZBvdUjD0iOwgTZt0hGZks5qbMwWgaJpZM4JZA5A&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=3VYqmJyUJudLw7jNaGhoKHxFYF6rUZoiciFnRd2hrXQ&m=PiEUP3JYQ7zaoxlnUds3craSOKNinnO28s6F6XVv4ZQ&s=xEUw_p7te7oedaO343ECC5zNHAiQR2bEpDcCHzsWUFA&e=>
> .
>


-- 
Graduate Research Assistant and NEUP Fellow
Computational Fluid Dynamics Research Group
Department of Nuclear Engineering
Texas A&M University
<lcarasik@tamu.edu>lcarasik@tamu.edu - (770)876-3895

**Comment by stgeke** [comment]
There is no question a technical report (say a pdf) is needed. The questions is, what's the primary source of documentation. Fore me a wiki is more interactive than a static document and it's more flexible when you want connect different informations (from multiple sources) together. 

@RonRahaman I agree, this would require major rewrite which is painful to do. 

This enhancement was just crossing my mind, feel free to close it.

**Comment by maxhutch** [comment]
I think that I understand what you are getting at, Stefan: use one set of
markdown sources to generate both a wiki and pdf manual. My concern is that
wiki's are best when they have a graphical layout without a clear start and
an end.  On the other hand, the manual needs to be projected onto a line.
There's probably a thoughtful way to layout the wiki such that, with the
addition of a few glue subsections, it can be linearized like that, but
that seems pretty difficult.

**Comment by RonRahaman** [comment]
@stgeke you've got some really good points, and do I think mid-level users would appreciate having the wiki (rather than diving into the full technical report).  

However, it's very important that the wiki and the technical report do not diverge. The wiki could easily get ahead of the technical report in crucial area.  Furthermore, @oanaoana has done a ton of work keeping the technical report up-to-date, and I want to maintain that momentum by working primarily on the technical report.

**Comment by RonRahaman** [comment]
@stgeke, what do you think about moving the [WordPress site](https://nek5000.mcs.anl.gov/) to the GitHub wiki?  The WordPress site was probably intended to solve the issues you mentioned (easily searchable, consolidating information from multiple sources, etc.).  However, it's really poorly organized and difficult to search.   It might even be easier to port the [old wiki](http://www.mcs.anl.gov/~oanam/old_page/index.html) over to a GitHub wiki.

**Comment by stgeke** [comment]
I was not involved in the change to WordPress, but I like you idea.

**Comment by RonRahaman** [comment]
It happened before my time, but I think most of the Nek folks are dissatisfied with move to WordPress (maybe @oanaoana could chime in).

As I understand it, the Math and Computer Science (MCS) Division here at Argonne used to maintain MediaWiki sites for us and other folks in MCS .  MediaWiki powers Wikipedia and does all the great stuff you'd want from a wiki.  That's probably why the old wiki was so great.  

However, MCS dropped support for MediaWiki and moved us towards WordPress.  I, for one, am pretty dissatisfied with WordPress, and would also support another option.  Plus, I wouldn't want to move the website *again* if MCS moves to another option.

**Comment by oanaoana** [comment]
Also the webpage, took time and did bring benefits. A proper homepage is needed, and wordpress is a publishing tool, as opposed to git which is a collaborative tool. I do not know who are these unhappy people, but I could have a discussion with them and follow their suggestions. 

As is the homepage did bring us some new collaborations, due to the gallery and exposure of Nek related work. For searchable info on nek one can do that in the manual, which yes could and should be extended.

**Comment by lcarasik** [comment]
I agree with @oanaoana.

**Comment by RonRahaman** [comment]
> Also the webpage, took time and did bring benefits... I do not know who are these unhappy people, but I could have a discussion with them and follow their suggestions.

No doubt.  I have some petty grievances with the WordPress site, but they're better addressed by some relatively minor changes to the website.  I got carried away.  

> For searchable info on nek one can do that in the manual, which yes could and should be extended.

Yeah, I do think this is the best position.  

The manual reflects a huge amount of effort on your part, @oanaoana, and it would be a waste of resources to duplicate that effort elsewhere.  If I may paraphrase @emerzari, he's expressed the same thing over email.   I think submitting issues and pull requests to NekDoc has been working great.  

@stgeke, may we close this issue for now?  It can always be reopened in the future.
