### ISSUE TITLE
Fill out the Averaging section of NekDocs

### ISSUE THREAD

**Issue by lcarasik** [Nek5000/NekDoc#120]
As a current user and someone teaching a few different new users, it would be helpful for http://nek5000.github.io/NekDoc/problem_setup/features.html?highlight=averaging#averaging to be filled out. 

Specifically, usage of the autoaverager subroutine and the best way to handle averaged field files in different subdirectories.

**Comment by lcarasik** [comment]
Below is compiling the information to help with this from the user forms.

https://lists.mcs.anl.gov/pipermail/nek5000-users/2017-November/004814.html

"Hi ZJ,

A quick search of the archives with keyword “avg_all” will give you answer to related questions:
https://lists.mcs.anl.gov/mailman/mmsearch/nek5000-users?config=nek5000-users.htsearch&restrict=&exclude=&method=and&format=short&sort=score&words=avg_all

avg_all is a collection of time-averaged information in the avg, rms and rm2 files. The avg files has time-averaged u,v and w; rms has time-averaged u^2, v^2 and w^2; and rm2 has uv, vw, and uw. The avg_all routines is located in navier5.f in case you want to get more information.

Typically the first step in post processing is to use the routine “auto_averager” to combine all the files output from avg_all. autoaverager takes as input the name of a file (example: fname1.list) which has a list of all the files that you want to combine (example: the contents of fname1.list will be: avgcasename0.f00001 avgcasename0.f00002 … Note- there should be only 1 filename per line in the fname1.list file). You can use the auto_averager routine to combine all your avgcasename0.f00* files and output them to a single file or do more post-processing with it. The quantities available in avg, rms and rm2 files are sufficient to get the actual urms, vrms velocities etc… Additionally, once you time-average the data using auto_averager, you can use space averaging routines such as z_avg etc… to average quantities in homogeneous direction of your domain.

It would also help if you specify what exactly are you trying to get from these avg_all files i.e. are you looking for rms velocities or something else?

Here is a snippet of my code that I have used in the past to post-process these files:
      call auto_averager(fname1)
      call copy(uk,vx)
      call copy(vk,vy)
      call copy(wk,vz)
      call col2(uk,uk,lt)
      call col2(vk,vk,lt)
      call col2(wk,wk,lt)
      call auto_averager(fname2)
      call sub2(vx,uk,lt)
      call sub2(vy,vk,lt)
      call sub2(vz,wk,lt)
      call z_avg(vxa,vx,gs_avg_hndl,nelxy,ifld)
      call z_avg(vya,vy,gs_avg_hndl,nelxy,ifld)
      call z_avg(vza,vz,gs_avg_hndl,nelxy,ifld)
      call outpost(vxa,vya,vza,vxa,vya,'   ')

Here fname1 has the list of all avgcasename0.f00* files and fname2 has the list of all the rmscasename0.f00* files.

Additional Discussions:
1. https://lists.mcs.anl.gov/mailman/htdig/nek5000-users/2018-February/005017.html
2. https://lists.mcs.anl.gov/mailman/htdig/nek5000-users/2018-July/005469.html
3. https://lists.mcs.anl.gov/mailman/htdig/nek5000-users/2017-October/004694.html - for turbulent heat fluxes

**Comment by dshaver-ANL** [comment]
Averaging itself is now documented. I would appreciate some help on using auto_averager.

**Comment by lcarasik** [comment]
This was address by the latest commit. The autoaverager issue was split out into #126
