### ISSUE TITLE
Documentation for all common block variables (NEKUSE, SIZE, etc.) relevant for the .usr file subroutines (userdat, userdat2, userchk, userbc, useric, uservp)

### ISSUE THREAD

**Issue by vulcanoffj** [Nek5000/NekDoc#127]
When working with the .usr file it can be obtuse trying to understand what variables are available to me at any given time. Once you understand where the common block files are, it then becomes an issue to understand the actual definitions of the variables and what they do. The lack of descriptions on the common block file combined with some less than intuitive naming schemes can make finding a path forward much more difficult. Understanding when I have to define my own variables (such as applying differential heating across a pipe etc.) is a more difficult endeavor than it should be.

**Comment by dshaver-ANL** [comment]
A reasonably complete list is here
https://nek5000.github.io/NekDoc/appendix.html#commonly-used-variables 
If this isn't what you had in mind, a specific request would be appreciated.

**Comment by vulcanoffj** [comment]
Diving into the common block folders as well, while it does clarify which variables I have at my disposal it doesn't explain their uses clearly and it's nice to have documentation explaining each for some of the more common calls like NEKUSE, INPUT, SIZE.


I've noticed now that I'm diving into stuff like calling Rayleigh I'm asking more questions like why are there ra1, ra2, ra3 etc and what defines the difference between them and things like that. That table is generally very useful especially when someone uses a new set for the first time.

**Comment by dshaver-ANL** [comment]
This should be satisfied with #128
