### ISSUE TITLE
Redundant information Quickstart section and README

### ISSUE THREAD

**Issue by stgeke** [Nek5000/NekDoc#32]
https://nek5000.github.io/NekDoc/quickstart.html
https://github.com/Nek5000/Nek5000/blob/master/README.md

**Comment by dshaver-ANL** [comment]
Is this really an issue?  As long as the two are consistent, the README is brief, and it points the user to the documentation for further info.  Thoughts?

**Comment by stgeke** [comment]
Well the current Quickstart is outdated but I know that Saumil is working on that including the tutorial.
