### ISSUE TITLE
parameter 2 incorrect in Case Setup File section

### ISSUE THREAD

**Issue by dshaver-ANL** [Nek5000/NekDoc#33]
parameter 2 is listed as kinematic viscosity (nu) in the table at the end of "Routines in .usr File" section.  It should be molecular viscosity (mu).  It is correct elsewhere in the documentation.

**Comment by cewasberg** [comment]
It is also incorrect in "Appendices"->"Available parameters" (PARAM2)
Pull request #21, regarding PARAM2, is not included in the online version.

**Comment by dshaver-ANL** [comment]
"Routines in .usr File" and "Appendices"->"Available parameters" have been updated.
