### ISSUE TITLE
Update ns_eqns to fix Re and Fr numbers - Pull #16 - Approved but not implemented

### ISSUE THREAD

**Issue by lcarasik** [Nek5000/NekDoc#38]
The pull request to fix some of the issues identified in Pull #16 were "approved" but not implemented.

**Comment by dshaver-ANL** [comment]
Reynolds number has been fixed.  The references to the Froude number were removed as this is considered a model which is the responsibility of the user.  However, a consistent non-dimensionalization of the user forcing function was added.
