### ISSUE TITLE
Description of error codes

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/NekDoc#57]
Would you consider documenting the numeric values and meanings of error codes produced by Nek?  When I'm using libnek5000 from other apps, it would be helpful if I could process the errors intelligently.

**Comment by stgeke** [comment]
What error codes are you talking about?

**Comment by RonRahaman** [comment]
I guess I described the problem wrong.  Theproblem is that Nek5000 returns 0 even even when there's an error.  Correct?  For example, `err_chk` will print an error message but it will still call `exitt`, which returns 0.

**Comment by stgeke** [comment]
Correct. So you want to make Nek5000 return a non-zero value in case of an error? In this case please open an issue on Nek5000.

**Comment by RonRahaman** [comment]
Thanks.  I understand this isn't a quick fix, and I appreciate you considering it.
