### ISSUE TITLE
default values for par file

### ISSUE THREAD

**Issue by dshaver-ANL** [Nek5000/NekDoc#60]
A list of the default values used by Nek for any key not specified in the .par file would be useful, e.g. if the 'dealiasing' key is omitted from the [GENERAL] section of the .par file, it gets set to 'yes'.

**Comment by stgeke** [comment]
Fixed in https://github.com/Nek5000/NekDoc/commit/2def9366adbc43048775d25c1e6bd7ad357b2cdc
