### ISSUE TITLE
Source-level Docs for Developer's Guide?

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/NekDoc#68]
What's the outlook for source-level documentation in the proposed developers guild (see Issue #65)?

If you're interested in bringing back the Doxygen, it seems we can still integrate it in the current Sphynx docs (see [this FAQ](http://www.sphinx-doc.org/en/master/faq.html#using-sphinx-with)).  I still have an ancient Doxyfile that simply generates the descriptions of the code structure (with links and whatnot).  Might be a good start.  However, since Nek doesn't have much Doxygen-formatted in-source comments, the resulting doc is still pretty bare.  I've heard rumors that KTH made some more progress with Doxygen (@pschlatt1, @adampep)?

If you're interested in a pure Sphynx solution, then we can either document in-source or out-of-source with [Sphinx domains](http://www.sphinx-doc.org/en/stable/domains.html).  

IMO, the main thing to consider is whether you want in-source or out-of-source docs.  I believe Doxygen would be better for in-source whereas Sphinx domains would be better for out-of-source.

**Comment by stgeke** [comment]
* We agreed to start with in-source documentation using Doxygen
* We are also considering a software design document explaining the different components and how the interfact (workflow, dataflow etc.).
