### ISSUE TITLE
Add PPLIST documentation?

### ISSUE THREAD

**Issue by maxhutch** [Nek5000/NekDoc#7]
There doesn't seem to be any description of the PPLIST options, e.g. BGQ, MPIIO, etc.  I started some [here](https://github.com/Nek5000/Nek5000/wiki/Build-options), but maybe it belongs in the doc as well or instead?

**Comment by dshaver-ANL** [comment]
Is this still relevant, or is it covered by the Build Options appendix?

**Comment by stgeke** [comment]
The PPLIST options are misssing. I guess it makes sense to add them.

**Comment by emerzari** [comment]
This was originally taken care in

https://github.com/Nek5000/NekDoc/pull/44

It looks like the table was removed in a recent quickrestart rewrite? I cant find it on the NekDoc anymore. I am not sure the QuickStart is the best place for it bu the modifying makenek section should be somewhere.

On Mar 9, 2018, at 2:55 AM, Stefan K. <notifications@github.com<mailto:notifications@github.com>> wrote:


The PPLIST options are misssing. I guess it makes sense to add them.

**Comment by stgeke** [comment]
I guess that was me when shuffling around some content. Let’s copy&paste the pplist options from the PR into the current build option section.

On 14 Mar 2018, at 10:51, emerzari <notifications@github.com <mailto:notifications@github.com> > wrote:

This was originally taken care in

https://github.com/Nek5000/NekDoc/pull/44

It looks like the table was removed in a recent quickrestart rewrite? I cant find it on the NekDoc anymore. I am not sure the QuickStart is the best place for it bu the modifying makenek section should be somewhere.

On Mar 9, 2018, at 2:55 AM, Stefan K. <notifications@github.com <mailto:notifications@github.com> <mailto:notifications@github.com <mailto:notifications@github.com> >> wrote:


The PPLIST options are misssing. I guess it makes sense to add them.
