### ISSUE TITLE
Updating "Quick Start"

### ISSUE THREAD

**Issue by RonRahaman** [Nek5000/NekDoc#9]
Section 2, "Quick Start", should be updated with instructions for the Git repo.  I intend to keep the instructions for the SVN repo, as well.

**Comment by lcarasik** [comment]
You may want to make sure the pathing in the "worked example" is modifed to reflect it as well. It looks like the pathing only would work for svn repo of Nek.

**Comment by RonRahaman** [comment]
Thanks, @lcarasik, will do.
