### ISSUE TITLE
description of .f00000 output file format is incorrect

### ISSUE THREAD

**Issue by dshaver-ANL** [Nek5000/NekDoc#90]

**Comment by dshaver-ANL** [comment]
@RonRahaman would you be able to help me with this? This should have come up in the fld_pyutils development.

**Comment by RonRahaman** [comment]
Sure, you can Assign it to me, and that will help me keep track of it

**Comment by RonRahaman** [comment]
Just to be clear, would you like this section to be updated?
https://nek5000.github.io/NekDoc/problem_setup/case_files.html#restart-output-files-f-05d

**Comment by dshaver-ANL** [comment]
yes
